### ISSUE TITLE
Generate Rare Cats, Adopt Success Popup Does Not Display Rarity

### ISSUE THREAD

**Issue by aibbones** [Schrodinger-AI/schrodinger-server#46]
### Description
Generate Rare Cats, Adopt Success Popup Does Not Display Rarity

### Steps To Reproduce
1. Log in
2. Generate 9th generation (cats with rarity tags)
3. Check the adopt success popup

### Current Behavior
-The adopt success popup does not display the rarity

### Expected Behavior
- The adopt success popup would display the rarity

### Environment
- Platform: PC

**Comment by house1313** [comment]
bug fixed in release 2.2.0
